name: Merge queue

on:
  merge_group:

jobs:
  nothing:
    runs-on: ubuntu-slim
    steps:
      - run: |
        echo "merge group, sleeping for 1 min"
        sleep 60
        echo "done sleeping"
