name: Merge queue

on:
  merge_group:

jobs:
  nothing:
    runs-on: ubuntu-slim
    steps:
      - name: sleep
        run: |
          echo "merge queue sleeping for 1 min"
          sleep 60
          echo "done sleeping"
